### PR TITLE
Trabalho REST Marcio Vergani

### PR DESCRIPTION
**Pull request by marcverg**
Trabalho REST Marcio V. - Meu delphi deu problema ao compilar.

### CODE REVIEW

**Comment by cesarforato** [comment]
Boa tarde Professor. Esquisito tava compilando aqui. Mas vou dar uma olhada.
Eu entreguei todas as atividades no prazo e estou reprovado na disciplina. É só por causa dessa atividade?

Enviado do meu iPhone

Em 11 de set de 2019, à(s) 19:59, marcverg <notifications@github.com<mailto:notifications@github.com>> escreveu:


Trabalho REST Marcio V. - Meu delphi deu problema ao compilar.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39

Commit Summary

  *   Add files via upload

File Changes

  *   M PizzariaGroup.groupproj<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-0> (30)
  *   M README.md<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-1> (3)
  *   M client/dpr/PizzariaFrontend.dpr<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-2> (20)
  *   M client/dpr/PizzariaFrontend.dproj<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-3> (1219)
  *   A client/dpr/PizzariaFrontend.dproj.local<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-4> (6)
  *   A client/dpr/PizzariaFrontend.identcache<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-5> (0)
  *   A client/dpr/PizzariaFrontend.res<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-6> (0)
  *   A client/dpr/PizzariaFrontend.stat<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-7> (10)
  *   A client/pas/ui/UFrmPrincipal.dfm<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-8> (109)
  *   A client/pas/ui/UFrmPrincipal.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-9> (68)
  *   M server/dpr/PizzariaBackend.dpr<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-10> (128)
  *   M server/dpr/PizzariaBackend.dproj<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-11> (1219)
  *   A server/dpr/PizzariaBackend.dproj.local<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-12> (2)
  *   A server/dpr/PizzariaBackend.dres<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-13> (0)
  *   A server/dpr/PizzariaBackend.identcache<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-14> (0)
  *   A server/dpr/PizzariaBackend.res<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-15> (0)
  *   A server/dpr/PizzariaBackend.stat<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-16> (10)
  *   A server/dpr/PizzariaBackendResource.rc<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-17> (1)
  *   A server/pas/controller/UPizzariaControllerImpl.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-18> (50)
  *   A server/pas/controller/__history/UPizzariaControllerImpl.pas.~1~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-19> (56)
  *   M server/pas/repository/UPedidoRepositoryImpl.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-20> (37)
  *   M server/pas/repository/UPedidoRepositoryIntf.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-21> (4)
  *   A server/pas/repository/__history/UPedidoRepositoryImpl.pas.~1~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-22> (63)
  *   A server/pas/repository/__history/UPedidoRepositoryImpl.pas.~2~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-23> (64)
  *   A server/pas/repository/__history/UPedidoRepositoryIntf.pas.~1~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-24> (18)
  *   M server/pas/service/UPedidoServiceImpl.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-25> (20)
  *   M server/pas/service/UPedidoServiceIntf.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-26> (4)
  *   A server/pas/service/__history/UPedidoServiceImpl.pas.~1~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-27> (82)
  *   A server/pas/service/__history/UPedidoServiceIntf.pas.~1~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-28> (17)
  *   A server/pas/wm/UWMPizzariaBackend.dfm<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-29> (13)
  *   A server/pas/wm/UWMPizzariaBackend.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-30> (46)
  *   A shared/pas/dto/UPedidoRealizaDTOImpl.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-31> (27)
  *   M shared/pas/dto/UPedidoRetornoDTOImpl.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-32> (38)
  *   M shared/pas/enum/UPizzaSaborEnum.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-33> (3)
  *   M shared/pas/enum/UPizzaTamanhoEnum.pas<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-34> (3)
  *   A shared/pas/enum/__history/UPizzaSaborEnum.pas.~1~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-35> (10)
  *   A shared/pas/enum/__history/UPizzaTamanhoEnum.pas.~1~<https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39/files#diff-36> (10)

Patch Links:

  *   https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39.patch
  *   https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/39.diff

**Comment by ebaptistella** [comment]
Boa noite Cesar.

Você já havia entregue (realizado o pull request) em 12/08 (
https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/18)
Suas notas são, 9.6, 10, 10, 10.



*--Eurides V. Baptistella**E-mail:* eurides.baptistella@gmail.com


Em qui, 12 de set de 2019 às 13:26, cesarforato <notifications@github.com>
escreveu:

**Comment by cesarforato** [comment]
Boa tarde Professor. Ah então blz, é que no ambiente estou reprovado, achei estranho. Mas se está tudo certo então blz. Obrigado

Enviado do meu iPhone

Em 12 de set de 2019, à(s) 19:11, Eurides Baptistella <notifications@github.com<mailto:notifications@github.com>> escreveu:

Boa noite Cesar.

Você já havia entregue (realizado o pull request) em 12/08 (
https://github.com/ebaptistella/10604-SD-EAD1530-SOAP/pull/18)
Suas notas são, 9.6, 10, 10, 10.



*--Eurides V. Baptistella**E-mail:* eurides.baptistella@gmail.com<mailto:eurides.baptistella@gmail.com>


Em qui, 12 de set de 2019 às 13:26, cesarforato <notifications@github.com<mailto:notifications@github.com>>
escreveu:

**Comment by ebaptistella** [comment]
ok

**Pull request closed without merging**
